#!/usr/bin/env node
// Generates src/assets/THIRD-PARTY-NOTICES.txt — the release-grade third-party
// license bundle shown in Settings → About → Open source licenses.
//
//   pnpm notices      (or: node scripts/generate-notices.mjs)
//
// Sources (all LOCAL — no network at generate time):
//   • Rust   — src-tauri/Cargo.lock → each crate's source in the cargo registry
//              cache (~/.cargo/registry/src), reading its actual LICENSE files.
//   • npm    — `pnpm licenses list --prod --json` → LICENSE files in node_modules.
//   • LibVLC — scripts/license-texts/LGPL-2.1.txt (canonical text, committed).
//   • Fonts  — src/assets/fonts/*-OFL.txt (+ Inter copyright).
//
// Texts are the ones the authors actually shipped, so copyright lines are exact.
// Re-run whenever dependencies change; commit the regenerated output.

import { readFileSync, writeFileSync, existsSync, readdirSync } from 'node:fs';
import { homedir } from 'node:os';
import { join } from 'node:path';
import { execSync } from 'node:child_process';

const ROOT = process.cwd();
const OUT = join(ROOT, 'src/assets/THIRD-PARTY-NOTICES.txt');
const SEP = '\n' + '='.repeat(78) + '\n';

const out = [];
out.push('SKALD — THIRD-PARTY NOTICES');
out.push('Generated by scripts/generate-notices.mjs — do not edit by hand.');
out.push(`Generated: ${new Date().toISOString()}`);
out.push('License texts below are taken verbatim from the components as shipped.');

const LICENSE_RE = /^(licen[cs]e|copying|notice|unlicense)([.\-_]?.*)?$/i;
function readLicenseTexts(dir) {
  if (!dir || !existsSync(dir)) return '';
  let files;
  try { files = readdirSync(dir); } catch { return ''; }
  const parts = [];
  for (const f of files.sort()) {
    if (LICENSE_RE.test(f)) {
      try {
        const t = readFileSync(join(dir, f), 'utf8').trim();
        if (t) parts.push(`[${f}]\n${t}`);
      } catch { /* unreadable — skip */ }
    }
  }
  return parts.join('\n\n');
}

// ── LibVLC (LGPL-2.1-or-later) ────────────────────────────────────────────────
out.push(SEP + 'AUDIO ENGINE — LibVLC (VLC media player)' + SEP);
out.push([
  'Skald bundles LibVLC (libvlc.dll, libvlccore.dll and VLC plugins under',
  'src-tauri/vlc-dist/) from the VideoLAN project. LibVLC is licensed under the GNU',
  'Lesser General Public License, version 2.1 or (at your option) any later version.',
  'It ships as separate, replaceable dynamic libraries (not statically linked), so a',
  'user may substitute their own build — satisfying the LGPL relink requirement.',
  'Corresponding source for the bundled version: https://www.videolan.org/vlc/download-sources.html',
  '',
].join('\n'));
out.push(readFileSync(join(ROOT, 'scripts/license-texts/LGPL-2.1.txt'), 'utf8').trim());

// ── Fonts (SIL OFL 1.1) ───────────────────────────────────────────────────────
out.push(SEP + 'FONTS — SIL Open Font License 1.1' + SEP);
out.push([
  'Inter',
  'Copyright (c) 2016 The Inter Project Authors (https://github.com/rsms/inter)',
  'Used under the SIL Open Font License 1.1. The OFL text is identical to the',
  'JetBrains Mono / Source Serif 4 copies reproduced below.',
  '',
].join('\n'));
for (const ff of ['JetBrainsMono-OFL.txt', 'SourceSerif4-OFL.txt']) {
  const p = join(ROOT, 'src/assets/fonts', ff);
  if (existsSync(p)) {
    out.push(`--- ${ff} ---`);
    out.push(readFileSync(p, 'utf8').trim());
    out.push('');
  }
}

// ── npm production dependencies ───────────────────────────────────────────────
out.push(SEP + 'NPM DEPENDENCIES (production)' + SEP);
let npmData = {};
try {
  npmData = JSON.parse(execSync('pnpm licenses list --prod --json', { encoding: 'utf8', maxBuffer: 128 * 1024 * 1024 }));
} catch (e) {
  out.push(`(failed to enumerate npm licenses: ${e.message})`);
}
const npmPkgs = [];
for (const [license, arr] of Object.entries(npmData)) {
  for (const p of Array.isArray(arr) ? arr : []) npmPkgs.push({ ...p, _license: license });
}
npmPkgs.sort((a, b) => a.name.localeCompare(b.name));
for (const p of npmPkgs) {
  const ver = Array.isArray(p.versions) ? p.versions.join(', ') : (p.version || '');
  out.push(`\n### ${p.name} ${ver} — ${p.license || p._license}`);
  const author = typeof p.author === 'string' ? p.author : p.author?.name;
  if (author) out.push(`Author: ${author}`);
  const text = readLicenseTexts(Array.isArray(p.paths) ? p.paths[0] : undefined);
  out.push(text || `(no LICENSE file in package; canonical text at spdx.org/licenses/${p.license || p._license})`);
}

// ── Rust crates ───────────────────────────────────────────────────────────────
out.push(SEP + 'RUST CRATES' + SEP);
const lock = readFileSync(join(ROOT, 'src-tauri/Cargo.lock'), 'utf8');
const crates = [];
for (const block of lock.split('[[package]]').slice(1)) {
  const n = block.match(/name = "([^"]+)"/);
  const v = block.match(/version = "([^"]+)"/);
  if (n && v) crates.push({ name: n[1], version: v[1] });
}
const regBase = join(homedir(), '.cargo', 'registry', 'src');
let indexDir = null;
try {
  const dirs = readdirSync(regBase);
  indexDir = dirs.find(d => d.startsWith('index.crates.io')) || dirs[0];
} catch { /* no cargo cache */ }
function crateDir(name, version) {
  if (!indexDir) return null;
  const d = join(regBase, indexDir, `${name}-${version}`);
  return existsSync(d) ? d : null;
}
function crateLicense(dir) {
  try {
    const toml = readFileSync(join(dir, 'Cargo.toml'), 'utf8');
    const m1 = toml.match(/^license\s*=\s*"([^"]+)"/m);
    if (m1) return m1[1];
    const m2 = toml.match(/^license-file\s*=\s*"([^"]+)"/m);
    if (m2) return `(license-file: ${m2[1]})`;
  } catch { /* no Cargo.toml */ }
  return '(unspecified)';
}
let rustCount = 0, rustMissing = 0, rustSkipped = 0;
for (const c of crates.sort((a, b) => a.name.localeCompare(b.name))) {
  if (c.name === 'skald') continue; // the app itself
  const dir = crateDir(c.name, c.version);
  // Crates with no extracted source were not built for this target (other-OS or
  // unused deps in the lock) — they aren't in the shipped binary, so skip them.
  if (!dir) { rustSkipped++; continue; }
  const lic = crateLicense(dir);
  out.push(`\n### ${c.name} ${c.version} — ${lic}`);
  const text = readLicenseTexts(dir);
  if (text) out.push(text);
  else { out.push(`(license text not found in crate; canonical text at spdx.org/licenses/${lic})`); rustMissing++; }
  rustCount++;
}

writeFileSync(OUT, out.join('\n') + '\n', 'utf8');
console.log(`Wrote ${OUT}`);
console.log(`npm packages: ${npmPkgs.length}; rust crates: ${rustCount} built (missing text: ${rustMissing}); skipped ${rustSkipped} non-built lock entries`);
